### ISSUE TITLE
Allow type inference from validation 

### ISSUE THREAD

**Issue by dresslerdemos** [demos-europe/edt#60]
Currently Symfony Validation is used to validate request data, however, phpstan is not able to infer the type from that, which increases the chance for type based bugs in the code.

Something like https://github.com/jbboehr/phpstan-laravel-validation is needed, but with a license that allows usage inside a MIT (Expat) licensed project, which is not the case with [AGPL v3+](https://www.gnu.org/licenses/agpl-3.0).

**Comment by dresslerdemos** [comment]
[`phpixie/validate`](https://phpixie.com/components/validate.html): type awareness doesn't seem to be build in; no phpstan compatibility was found

**Comment by dresslerdemos** [comment]
[`zendframework/zend-validator`](https://packagist.org/packages/zendframework/zend-validator) is no longer maintained and recommends [`laminas/laminas-validator`](https://packagist.org/packages/laminas/laminas-validator)

**Comment by dresslerdemos** [comment]
[`Respect/Validation`](https://github.com/Respect/Validation): no phpstan extension was found

**Comment by joorei** [comment]
It is quite possible that no library exists that covers all requirements. Also, there is no major concern in keeping Symfony Validation:

* The drawback of missing built-in phpstan support can be mitigated by hard-coding type hints for the logic after the validation as is already done in at least one validator implementations.
* Depending on a component from a large framework may be problematic in case an application needs to use a different version than the one supported by this library. However, Symfony Validation is not the only Symfony component used and trying to keep this library working without any Symfony components will not be done without a specific use case.

Due to those considerations, the investigation is closed for now.
